import 'package:flutter/widgets.dart';
import '../services/service_scope.dart';

/// Centralized localization dictionary for the 10 disaster-region languages:
/// English (en), Hindi (hi), Odia (or), Bengali (bn), Assamese (as),
/// Malayalam (ml), Gujarati (gu), Maithili (mai), Bodo (brx), Telugu (te).
class AppLocalizations {
  static String codeForLanguage(String language) {
    final lower = language.toLowerCase();
    if (lower.contains('hindi') || lower.contains('हिन्दी') || lower == 'hi') return 'hi';
    if (lower.contains('odia') || lower.contains('ଓଡ଼ିଆ') || lower == 'or') return 'or';
    if (lower.contains('bengali') || lower.contains('বাংলা') || lower == 'bn') return 'bn';
    if (lower.contains('assamese') || lower.contains('অসমীয়া') || lower == 'as') return 'as';
    if (lower.contains('malayalam') || lower.contains('മലയാളം') || lower == 'ml') return 'ml';
    if (lower.contains('gujarati') || lower.contains('ગુજરાતી') || lower == 'gu') return 'gu';
    if (lower.contains('maithili') || lower.contains('मैथिली') || lower == 'mai') return 'mai';
    if (lower.contains('bodo') || lower.contains('बड़ो') || lower == 'brx') return 'brx';
    if (lower.contains('telugu') || lower.contains('తెలుగు') || lower == 'te') return 'te';
    return 'en';
  }

  static String tr(BuildContext context, String key, [Map<String, String>? params]) {
    String langCode = 'en';
    try {
      final service = EmergencyServiceScope.of(context);
      langCode = codeForLanguage(service.selectedLanguage);
    } catch (_) {}

    String translation = _strings[langCode]?[key] ?? _strings['en']?[key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        translation = translation.replaceAll('{$paramKey}', paramValue);
      });
    }
    return translation;
  }

  static const Map<String, Map<String, String>> _strings = {
    // -------------------------------------------------------------
    // ENGLISH (en)
    // -------------------------------------------------------------
    'en': {
      'tagline': 'OFFLINE EMERGENCY MESH NETWORK',
      'welcome_desc': 'Decentralized peer-to-peer communication when cellular towers and power grids fail during floods and cyclones.',
      'get_started': 'Get Started',
      'already_configured': 'Already configured? Go to Home',
      'select_language': 'Select your language',
      'language_preference': 'Language Preference',
      'disaster_coverage_desc': 'Coverage for disaster-prone regions across Assam, Odisha, Bihar, West Bengal, Kerala, Gujarat, and coastal cyclone zones.',
      'continue_btn': 'Continue',
      'your_details': 'Your details',
      'personal_info': 'Personal Information',
      'gov_id_hint': 'Enter your official details as shown on government ID (Aadhaar / Voter ID).',
      'take_photo': 'Take Photo',
      'choose_gallery': 'Choose from Gallery',
      'select_profile_photo': 'Select Profile Photo',
      'change_photo': 'Change photo',
      'add_photo': 'Add photo',
      'full_name': 'Full Name (as on government ID)',
      'name_hint': 'e.g. Rahul Sharma',
      'name_req': 'Please enter your full official name',
      'contact_number': 'Mobile / Contact Number',
      'phone_hint': 'e.g. +91 98765 43210',
      'phone_req': 'Please enter your contact number',
      'date_of_birth': 'Date of Birth',
      'dob_req': 'Please enter your date of birth',
      'dob_invalid': 'Please enter a valid date in DD/MM/YYYY format',
      'current_location': 'Current Location',
      'use_current_location': 'Use current location',
      'location_hint': 'e.g. Shelter 3, Guwahati Central',
      'location_req': 'Please provide your current area/shelter location',
      'acquiring_location': 'Acquiring real GPS location...',
      'location_services_disabled': 'Location services are disabled. Please enable GPS in device settings.',
      'location_permission_denied': 'Location permission denied.',
      'location_permission_denied_forever': 'Location permission permanently denied. Enable in App Settings.',
      'emergency_contacts': 'Emergency Contacts',
      'add_trusted_contacts': 'Add Trusted Contacts',
      'contacts_desc': 'Add at least one family member or emergency contact to notify during disaster.',
      'add_contact': 'Add Contact',
      'contact_name': 'Contact Name',
      'relationship': 'Relationship',
      'phone_number': 'Phone Number',
      'save_profile_continue': 'Save Profile & Continue',
      'skip_for_now': 'Skip for now',
      'profile_complete': 'Profile Setup Complete',
      'ready_to_connect': 'Your emergency profile is ready. You are now discoverable over the Sahara offline mesh.',
      'enter_sahara_home': 'Enter Sahara Home',
      'mesh_active': 'Mesh Active',
      'mesh_inactive': 'Mesh Inactive',
      'battery': 'Battery',
      'relays': 'Relays',
      'peers_nearby': 'Peers nearby',
      'emergency_sos': 'EMERGENCY SOS',
      'tap_sos_hint': 'Tap in life-threatening emergency',
      'sos_active': 'SOS ACTIVE',
      'emergency_broadcast': 'Emergency Broadcast',
      'active_badge': '{count} ACTIVE',
      'send_emergency_broadcast': 'Send emergency broadcast',
      'no_broadcasts': 'No emergency broadcasts in your sector.',
      'comm_and_contacts': 'COMMUNICATION & CONTACTS',
      'messages': 'Messages',
      'conversations_count': '{count} conversations • Store-and-forward active',
      'family': 'Family',
      'family_reachable_count': '{reachable} of {total} reachable over mesh',
      'nearby_people': 'Nearby People',
      'nearby_detected_count': '{count} mesh peers detected in range',
      'people_in_range': '{count} People Discovered in Range',
      'search_nearby_hint': 'Search people by name, phone or location...',
      'no_peers_found': 'No nearby peers matching "{query}"',
      'reachable': 'Reachable',
      'unreachable': 'Unreachable',
      'direct': 'Direct',
      'hops': '{count} hops',
      'hop': '1 hop',
      'ping': 'Ping',
      'ping_sent_to': 'Ping sent to {name}',
      'message': 'Message',
      'add_to_family': 'Add to Family',
      'added_to_family': 'Added {name} to Family',
      'broadcast_severity': 'BROADCAST SEVERITY',
      'severity_advisory': 'Advisory',
      'severity_warning': 'Warning',
      'severity_evacuation': 'Evacuation',
      'quick_suggestions': 'QUICK SUGGESTIONS (TAP TO INSERT)',
      'broadcast_message': 'BROADCAST MESSAGE',
      'enter_broadcast_hint': 'Enter emergency message...',
      'broadcast_button': 'BROADCAST MESSAGE',
      'broadcast_sent': 'BROADCAST SENT',
      'recipients_reached': 'Recipients reached',
      'relays_count': 'Relays',
      'compose_another': 'Compose Another Broadcast',
      'return_to_home': 'Return to Home',
      'cancel_sos': 'CANCEL SOS',
      'hold_for_sos': 'HOLD FOR 3 SECONDS TO TRIGGER SOS',
      'distress_beacon_active': 'BROADCASTING DISTRESS BEACON',
      'sos_broadcast_notice': 'Emergency SOS active across all relays',
      'ping_all_family': 'Ping All Family',
      'add_family_member': 'Add Family Member',
      'emergency_messages': 'Emergency Messages',
      'p2p_notice': 'P2P store-and-forward mesh routing active • Offline',
      'search': 'Search',
      'cancel': 'Cancel',
      'save': 'Save',
      'enable_location_services': 'Enable Location Services',
      'enable_location_services_desc': 'Location services (GPS) are turned off on your device. Sahara requires location services to determine your emergency coordinates.',
      'open_settings': 'Open Settings',
      'location_permission_required': 'Location Permission Required',
      'location_permission_settings_desc': 'Location permission was denied. Please allow location access in Sahara app settings to detect your coordinates.',
      'location_detected': 'Location detected successfully',
      'acquiring_gps_fix': 'Acquiring GPS fix...',
      'gps_active': 'GPS Active',
      'search_people_placeholder': 'Search people by name or phone number',
      'no_people_found': 'No people or contacts found',
      'all_contacts': 'All Contacts & Nearby',
      'retry': 'Retry',
    },

    // -------------------------------------------------------------
    // HINDI (hi)
    // -------------------------------------------------------------
    'hi': {
      'tagline': 'ऑफलाइन आपातकालीन मेश नेटवर्क',
      'welcome_desc': 'बाढ़ और चक्रवात के समय जब सेल टॉवर और बिजली ग्रिड विफल हो जाएं, तब विकेंद्रीकृत पीयर-टू-पीयर संचार।',
      'get_started': 'शुरू करें',
      'already_configured': 'पहले से कॉन्फ़िगर है? होम पर जाएं',
      'select_language': 'अपनी भाषा चुनें',
      'language_preference': 'भाषा प्राथमिकता',
      'disaster_coverage_desc': 'असम, ओडिशा, बिहार, पश्चिम बंगाल, केरल, गुजरात और तटीय चक्रवात क्षेत्रों के लिए कवरेज।',
      'continue_btn': 'आगे बढ़ें',
      'your_details': 'आपका विवरण',
      'personal_info': 'व्यक्तिगत जानकारी',
      'gov_id_hint': 'सरकारी पहचान पत्र (आधार / वोटर आईडी) के अनुसार अपना विवरण दर्ज करें।',
      'take_photo': 'फ़ोटो खींचें',
      'choose_gallery': 'गैलरी से चुनें',
      'select_profile_photo': 'प्रोफ़ाइल फ़ोटो चुनें',
      'change_photo': 'फ़ोटो बदलें',
      'add_photo': 'फ़ोटो जोड़ें',
      'full_name': 'पूरा नाम (सरकारी पहचान पत्र के अनुसार)',
      'name_hint': 'उदा. राहुल शर्मा',
      'name_req': 'कृपया अपना पूरा आधिकारिक नाम दर्ज करें',
      'contact_number': 'मोबाइल / संपर्क नंबर',
      'phone_hint': 'उदा. +91 98765 43210',
      'phone_req': 'कृपया अपना संपर्क नंबर दर्ज करें',
      'date_of_birth': 'जन्म तिथि',
      'dob_req': 'कृपया अपनी जन्म तिथि दर्ज करें',
      'dob_invalid': 'कृपया DD/MM/YYYY प्रारूप में मान्य तिथि दर्ज करें',
      'current_location': 'वर्तमान स्थान',
      'use_current_location': 'वर्तमान स्थान का उपयोग करें',
      'location_hint': 'उदा. शेल्टर 3, गुवाहाटी सेंट्रल',
      'location_req': 'कृपया अपना वर्तमान क्षेत्र/आश्रय स्थान दर्ज करें',
      'acquiring_location': 'वास्तविक जीपीएस स्थान प्राप्त किया जा रहा है...',
      'location_services_disabled': 'स्थान सेवाएं अक्षम हैं। कृपया डिवाइस सेटिंग्स में GPS चालू करें।',
      'location_permission_denied': 'स्थान अनुमति अस्वीकृत।',
      'location_permission_denied_forever': 'स्थान अनुमति स्थायी रूप से अस्वीकृत। ऐप सेटिंग्स में सक्षम करें।',
      'emergency_contacts': 'आपातकालीन संपर्क',
      'add_trusted_contacts': 'विश्वसनीय संपर्क जोड़ें',
      'contacts_desc': 'आपदा के दौरान सूचित करने के लिए कम से कम एक परिवार के सदस्य या आपातकालीन संपर्क को जोड़ें।',
      'add_contact': 'संपर्क जोड़ें',
      'contact_name': 'संपर्क का नाम',
      'relationship': 'संबंध',
      'phone_number': 'फ़ोन नंबर',
      'save_profile_continue': 'प्रोफ़ाइल सहेजें और आगे बढ़ें',
      'skip_for_now': 'अभी छोड़ें',
      'profile_complete': 'प्रोफ़ाइल सेटअप पूर्ण',
      'ready_to_connect': 'आपकी आपातकालीन प्रोफ़ाइल तैयार है। अब आप सहारा ऑफलाइन मेश पर दृश्यमान हैं।',
      'enter_sahara_home': 'सहारा होम में प्रवेश करें',
      'mesh_active': 'मेश सक्रिय',
      'mesh_inactive': 'मेश निष्क्रिय',
      'battery': 'बैटरी',
      'relays': 'रिले',
      'peers_nearby': 'निकटतम लोग',
      'emergency_sos': 'आपातकालीन एसओएस',
      'tap_sos_hint': 'जान को खतरा होने पर दबाएं',
      'sos_active': 'एसओएस सक्रिय',
      'emergency_broadcast': 'आपातकालीन प्रसारण',
      'active_badge': '{count} सक्रिय',
      'send_emergency_broadcast': 'आपातकालीन प्रसारण भेजें',
      'no_broadcasts': 'आपके क्षेत्र में कोई आपातकालीन प्रसारण नहीं है।',
      'comm_and_contacts': 'संचार एवं संपर्क',
      'messages': 'संदेश',
      'conversations_count': '{count} बातचीत • स्टोर-एंड-फॉरवर्ड सक्रिय',
      'family': 'परिवार',
      'family_reachable_count': '{reachable} / {total} मेश पर संपर्क योग्य',
      'nearby_people': 'आस-पास के लोग',
      'nearby_detected_count': '{count} मेश साथी सीमा में मिले',
      'people_in_range': '{count} मेश रेंज में मिले लोग',
      'search_nearby_hint': 'नाम, फोन या स्थान से खोजें...',
      'no_peers_found': '"{query}" से मेल खाता कोई साथी नहीं मिला',
      'reachable': 'पहुंच योग्य',
      'unreachable': 'पहुंच से बाहर',
      'direct': 'प्रत्यक्ष',
      'hops': '{count} हॉप',
      'hop': '1 हॉप',
      'ping': 'पिंग करें',
      'ping_sent_to': '{name} को पिंग भेजा गया',
      'message': 'संदेश',
      'add_to_family': 'परिवार में जोड़ें',
      'added_to_family': '{name} को परिवार में जोड़ा गया',
      'broadcast_severity': 'प्रसारण गंभीरता स्तर',
      'severity_advisory': 'सलाह',
      'severity_warning': 'चेतावनी',
      'severity_evacuation': 'निकासी',
      'quick_suggestions': 'त्वरित सुझाव (सम्मिलित करने के लिए टैप करें)',
      'broadcast_message': 'संदेश प्रसारित करें',
      'enter_broadcast_hint': 'आपातकालीन संदेश दर्ज करें...',
      'broadcast_button': 'संदेश प्रसारित करें',
      'broadcast_sent': 'प्रसारण भेजा गया',
      'recipients_reached': 'प्राप्तकर्ता पहुंचे',
      'relays_count': 'रिले',
      'compose_another': 'एक और संदेश लिखें',
      'return_to_home': 'मुख्य पृष्ठ पर लौटें',
      'cancel_sos': 'एसओएस रद्द करें',
      'hold_for_sos': 'एसओएस के लिए 3 सेकंड दबाकर रखें',
      'distress_beacon_active': 'संकट संकेत प्रसारित हो रहा है',
      'sos_broadcast_notice': 'सभी रिले पर आपातकालीन एसओएस सक्रिय',
      'ping_all_family': 'पूरे परिवार को पिंग करें',
      'add_family_member': 'परिवार का सदस्य जोड़ें',
      'emergency_messages': 'आपातकालीन संदेश',
      'p2p_notice': 'P2P स्टोर-एंड-फॉरवर्ड मेश रूटिंग सक्रिय • ऑफलाइन',
      'search': 'खोजें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
    },

    // -------------------------------------------------------------
    // ODIA (or)
    // -------------------------------------------------------------
    'or': {
      'tagline': 'ଅଫଲାଇନ୍ ଜରୁରୀକାଳୀନ ମେଶ୍ ନେଟୱାର୍କ',
      'welcome_desc': 'ବନ୍ୟା ଏବଂ ବାତ୍ୟା ସମୟରେ ମୋବାଇଲ୍ ଟାୱାର ବିଫଳ ହେଲେ ବିକେନ୍ଦ୍ରୀକୃତ ଯୋଗାଯୋଗ।',
      'get_started': 'ଆରମ୍ଭ କରନ୍ତୁ',
      'already_configured': 'ପୂର୍ବରୁ ପ୍ରସ୍ତୁତ ଅଛି? ହୋମ୍ କୁ ଯାଆନ୍ତୁ',
      'select_language': 'ଆପଣଙ୍କର ଭାଷା ବାଛନ୍ତୁ',
      'language_preference': 'ଭାଷା ପସନ୍ଦ',
      'disaster_coverage_desc': 'ଓଡ଼ିଶା, ଆସାମ, ବିହାର, ପଶ୍ଚିମବଙ୍ଗ, କେରଳ, ଗୁଜରାଟ ଏବଂ ଉପକୂଳବର୍ତ୍ତୀ ଅଞ୍ଚଳ ପାଇଁ ଉପଲବ୍ଧ।',
      'continue_btn': 'ଆଗକୁ ବଢ଼ନ୍ତୁ',
      'your_details': 'ଆପଣଙ୍କ ବିବରଣୀ',
      'personal_info': 'ବ୍ୟକ୍ତିଗତ ସୂଚନା',
      'gov_id_hint': 'ସରକାରୀ ପରିଚୟ ପତ୍ର (ଆଧାର / ଭୋଟର କାର୍ଡ) ଅନୁସାରେ ନିଜର ବିବରଣୀ ଦିଅନ୍ତୁ।',
      'take_photo': 'ଫଟୋ ଉଠାନ୍ତୁ',
      'choose_gallery': 'ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ',
      'select_profile_photo': 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ ବାଛନ୍ତୁ',
      'change_photo': 'ଫଟୋ ବଦଳାନ୍ତୁ',
      'add_photo': 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ',
      'full_name': 'ସମ୍ପୂର୍ଣ୍ଣ ନାମ (ସରକାରୀ ଆଇଡି ଅନୁସାରେ)',
      'name_hint': 'ଯଥା: ରାହୁଲ ଶର୍ମା',
      'name_req': 'ଦୟାକରି ଆପଣଙ୍କ ସମ୍ପୂର୍ଣ୍ଣ ସରକାରୀ ନାମ ଲେଖନ୍ତୁ',
      'contact_number': 'ମୋବାଇଲ୍ / ଯୋଗାଯୋଗ ନମ୍ବର',
      'phone_hint': 'ଯଥା: +91 98765 43210',
      'phone_req': 'ଦୟାକରି ଆପଣଙ୍କ ଯୋଗାଯୋଗ ନମ୍ବର ଦିଅନ୍ତୁ',
      'date_of_birth': 'ଜନ୍ମ ତାରିଖ',
      'dob_req': 'ଦୟାକରି ଆପଣଙ୍କ ଜନ୍ମ ତାରିଖ ଦିଅନ୍ତୁ',
      'dob_invalid': 'ଦୟାକରି DD/MM/YYYY ଫର୍ମାଟରେ ବୈଧ ତାରିଖ ଦିଅନ୍ତୁ',
      'current_location': 'ବର୍ତ୍ତମାନର ସ୍ଥାନ',
      'use_current_location': 'ବର୍ତ୍ତମାନର ସ୍ଥାନ ବ୍ୟବହାର କରନ୍ତୁ',
      'location_hint': 'ଯଥା: ଆଶ୍ରୟସ୍ଥଳୀ ୩, କଟକ',
      'location_req': 'ଦୟାକରି ବର୍ତ୍ତମାନର ସ୍ଥାନ ପ୍ରଦାନ କରନ୍ତୁ',
      'acquiring_location': 'ପ୍ରକୃତ ଜିପିଏସ୍ ସ୍ଥାନ ଖୋଜାଯାଉଛି...',
      'location_services_disabled': 'ସ୍ଥାନ ସେବା ବନ୍ଦ ଅଛି। ଦୟାକରି GPS ଚାଲୁ କରନ୍ତୁ।',
      'location_permission_denied': 'ସ୍ଥାନ ଅନୁମତି ପ୍ରତ୍ୟାଖ୍ୟାନ ହୋଇଛି।',
      'location_permission_denied_forever': 'ସ୍ଥାନ ଅନୁମତି ସ୍ଥାୟୀ ଭାବରେ ପ୍ରତ୍ୟାଖ୍ୟାନ ହୋଇଛି।',
      'emergency_contacts': 'ଜରୁରୀକାଳୀନ ଯୋଗାଯୋଗ',
      'add_trusted_contacts': 'ବିଶ୍ୱସ୍ତ ସମ୍ପର୍କ ଯୋଡ଼ନ୍ତୁ',
      'contacts_desc': 'ବିପର୍ଯ୍ୟୟ ସମୟରେ ଜଣାଇବା ପାଇଁ ଅତି କମରେ ଜଣେ ପରିବାର ସଦସ୍ୟ ଯୋଡ଼ନ୍ତୁ।',
      'add_contact': 'ସମ୍ପର୍କ ଯୋଡ଼ନ୍ତୁ',
      'contact_name': 'ସମ୍ପର୍କଙ୍କ ନାମ',
      'relationship': 'ସମ୍ପର୍କ',
      'phone_number': 'ଫୋନ୍ ନମ୍ବର',
      'save_profile_continue': 'ପ୍ରୋଫାଇଲ୍ ସାଇତି ଆଗକୁ ବଢ଼ନ୍ତୁ',
      'skip_for_now': 'ଏବେ ବାଦ୍ ଦିଅନ୍ତୁ',
      'profile_complete': 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପୂର୍ଣ୍ଣ ହେଲା',
      'ready_to_connect': 'ଆପଣଙ୍କ ଜରୁରୀକାଳୀନ ପ୍ରୋଫାଇଲ୍ ପ୍ରସ୍ତୁତ। ଆପଣ ସାହାରା ମେଶ୍ ରେ ଯୋଡ଼ି ହୋଇଗଲେ।',
      'enter_sahara_home': 'ସାହାରା ହୋମ୍ ପ୍ରବେଶ କରନ୍ତୁ',
      'mesh_active': 'ମେଶ୍ ସକ୍ରିୟ',
      'mesh_inactive': 'ମେଶ୍ ନିଷ୍କ୍ରିୟ',
      'battery': 'ବ୍ୟାଟେରୀ',
      'relays': 'ରିଲେ',
      'peers_nearby': 'ନିକଟସ୍ଥ ଲୋକ',
      'emergency_sos': 'ଜରୁରୀକାଳୀନ ଏସଓଏସ',
      'tap_sos_hint': 'ଜୀବନ ପ୍ରତି ବିପଦ ଥିଲେ ଦବାନ୍ତୁ',
      'sos_active': 'ଏସଓଏସ ସକ୍ରିୟ',
      'emergency_broadcast': 'ଜରୁରୀକାଳୀନ ପ୍ରସାରଣ',
      'active_badge': '{count} ସକ୍ରିୟ',
      'send_emergency_broadcast': 'ଜରୁରୀକାଳୀନ ପ୍ରସାରଣ ପଠାନ୍ତୁ',
      'no_broadcasts': 'ଆପଣଙ୍କ ଅଞ୍ଚଳରେ କୌଣସି ଜରୁରୀ ପ୍ରସାରଣ ନାହିଁ।',
      'comm_and_contacts': 'ଯୋଗାଯୋଗ ଏବଂ ସମ୍ପର୍କ',
      'messages': 'ସନ୍ଦେଶ',
      'conversations_count': '{count} ବାର୍ତ୍ତାଳାପ • ଷ୍ଟୋର୍-ଆଣ୍ଡ-ଫରୱାର୍ଡ ସକ୍ରିୟ',
      'family': 'ପରିବାର',
      'family_reachable_count': '{reachable} / {total} ମେଶ୍ ରେ ଉପଲବ୍ଧ',
      'nearby_people': 'ନିକଟସ୍ଥ ଲୋକ',
      'nearby_detected_count': '{count} ଜଣ ପରିସରରେ ଚିହ୍ନଟ',
      'people_in_range': '{count} ମେଶ୍ ପରିସରରେ ମିଳିଥିବା ଲୋକ',
      'search_nearby_hint': 'ନାମ, ଫୋନ୍ କିମ୍ବା ସ୍ଥାନ ଦ୍ୱାରା ଖୋଜନ୍ତୁ...',
      'no_peers_found': '"{query}" ସହିତ କୌଣସି ବ୍ୟକ୍ତି ମିଳିଲେ ନାହିଁ',
      'reachable': 'ଉପଲବ୍ଧ',
      'unreachable': 'ଅନୁପଲବ୍ଧ',
      'direct': 'ସିଧାସଳଖ',
      'hops': '{count} ହପ୍',
      'hop': '1 ହପ୍',
      'ping': 'ପିଙ୍ଗ୍ କରନ୍ତୁ',
      'ping_sent_to': '{name} କୁ ପିଙ୍ଗ୍ ପଠାଗଲା',
      'message': 'ସନ୍ଦେଶ',
      'add_to_family': 'ପରିବାରରେ ଯୋଡ଼ନ୍ତୁ',
      'added_to_family': '{name} ଙ୍କୁ ପରିବାରରେ ଯୋଡ଼ାଗଲା',
      'broadcast_severity': 'ପ୍ରସାରଣ ଗୁରୁତ୍ୱ',
      'severity_advisory': 'ପରାମର୍ଶ',
      'severity_warning': 'ଚେତାବନୀ',
      'severity_evacuation': 'ସ୍ଥାନାନ୍ତରଣ',
      'quick_suggestions': 'ତୁରନ୍ତ ପରାମର୍ଶ (ଯୋଡ଼ିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ)',
      'broadcast_message': 'ସନ୍ଦେଶ ପ୍ରସାରଣ କରନ୍ତୁ',
      'enter_broadcast_hint': 'ଜରୁରୀ ସନ୍ଦେଶ ଲେଖନ୍ତୁ...',
      'broadcast_button': 'ସନ୍ଦେଶ ପ୍ରସାରଣ କରନ୍ତୁ',
      'broadcast_sent': 'ପ୍ରସାରଣ ପଠାଗଲା',
      'recipients_reached': 'ପ୍ରାପ୍ତକର୍ତ୍ତାଙ୍କ ନିକଟରେ ପହଞ୍ଚିଛି',
      'relays_count': 'ରିଲେ',
      'compose_another': 'ଅନ୍ୟ ଏକ ସନ୍ଦେଶ ଲେଖନ୍ତୁ',
      'return_to_home': 'ମୁଖ୍ୟ ପୃଷ୍ଠାକୁ ଫେରନ୍ତୁ',
      'cancel_sos': 'ଏସଓଏସ ବାତିଲ କରନ୍ତୁ',
      'hold_for_sos': 'ଏସଓଏସ ପାଇଁ ୩ ସେକେଣ୍ଡ ଧରି ରଖନ୍ତୁ',
      'distress_beacon_active': 'ସଙ୍କଟ ସଙ୍କେତ ପ୍ରସାରଣ ଚାଲିଛି',
      'sos_broadcast_notice': 'ସମସ୍ତ ରିଲେ ରେ ଜରୁରୀ ଏସଓଏସ ସକ୍ରିୟ',
      'ping_all_family': 'ସମସ୍ତ ପରିବାରକୁ ପିଙ୍ଗ୍ କରନ୍ତୁ',
      'add_family_member': 'ପରିବାର ସଦସ୍ୟ ଯୋଡ଼ନ୍ତୁ',
      'emergency_messages': 'ଜରୁରୀ ସନ୍ଦେଶ',
      'p2p_notice': 'P2P ଷ୍ଟୋର୍-ଆଣ୍ଡ-ଫରୱାର୍ଡ ମେଶ୍ ସକ୍ରିୟ • ଅଫଲାଇନ୍',
      'search': 'ଖୋଜନ୍ତୁ',
      'cancel': 'ବାତିଲ କରନ୍ତୁ',
      'save': 'ସାଇତନ୍ତୁ',
    },

    // -------------------------------------------------------------
    // BENGALI (bn)
    // -------------------------------------------------------------
    'bn': {
      'tagline': 'অফলাইন জরুরি মেশ নেটওয়ার্ক',
      'welcome_desc': 'বন্যা ও ঘূর্ণিঝড়ের সময় মোবাইল নেটওয়ার্ক বন্ধ হলেও সরাসরি যোগাযোগ ব্যবস্থা।',
      'get_started': 'শুরু করুন',
      'already_configured': 'ইতিমধ্যে কনফিগার করা? হোমে যান',
      'select_language': 'আপনার ভাষা নির্বাচন করুন',
      'language_preference': 'ভাষার পছন্দ',
      'disaster_coverage_desc': 'আসাম, ওড়িশা, বিহার, পশ্চিমবঙ্গ, কেরালা, গুজরাট ও উপকূলীয় দুর্যোগ অঞ্চলের জন্য।',
      'continue_btn': 'এগিয়ে যান',
      'your_details': 'আপনার বিবরণ',
      'personal_info': 'ব্যক্তিগত তথ্য',
      'gov_id_hint': 'সরকারি পরিচয়পত্র (আধার / ভোটার কার্ড) অনুযায়ী আপনার তথ্য দিন।',
      'take_photo': 'ছবি তুলুন',
      'choose_gallery': 'গ্যালারি থেকে বেছে নিন',
      'select_profile_photo': 'প্রোফাইল ছবি নির্বাচন করুন',
      'change_photo': 'ছবি পরিবর্তন করুন',
      'add_photo': 'ছবি যুক্ত করুন',
      'full_name': 'সম্পূর্ণ নাম (সরকারি আইডি অনুযায়ী)',
      'name_hint': 'যেমন: রাহুল শর্মা',
      'name_req': 'আপনার সম্পূর্ণ সরকারি নাম লিখুন',
      'contact_number': 'মোবাইল / যোগাযোগের নম্বর',
      'phone_hint': 'যেমন: +91 98765 43210',
      'phone_req': 'অনুগ্রহ করে আপনার যোগাযোগের নম্বর দিন',
      'date_of_birth': 'জন্ম তারিখ',
      'dob_req': 'অনুগ্রহ করে জন্ম তারিখ দিন',
      'dob_invalid': 'DD/MM/YYYY ফরম্যাটে সঠিক তারিখ দিন',
      'current_location': 'বর্তমান অবস্থান',
      'use_current_location': 'বর্তমান অবস্থান ব্যবহার করুন',
      'location_hint': 'যেমন: আশ্রয়কেন্দ্র ৩, কলকাতা',
      'location_req': 'আপনার বর্তমান এলাকা বা আশ্রয়ের অবস্থান দিন',
      'acquiring_location': 'আসল জিপিএস অবস্থান নেওয়া হচ্ছে...',
      'location_services_disabled': 'অবস্থান পরিষেবা নিষ্ক্রিয়। জিপিএস চালু করুন।',
      'location_permission_denied': 'অবস্থান অনুমতি প্রত্যাখ্যাত।',
      'location_permission_denied_forever': 'অবস্থান অনুমতি স্থায়ীভাবে বন্ধ।',
      'emergency_contacts': 'জরুরি পরিচিতি',
      'add_trusted_contacts': 'বিশ্বস্ত পরিচিতি যুক্ত করুন',
      'contacts_desc': 'দুর্যোগের সময় যোগাযোগের জন্য অন্তত একজন পরিবারের সদস্য যুক্ত করুন।',
      'add_contact': 'পরিচিতি যোগ করুন',
      'contact_name': 'পরিচিতির নাম',
      'relationship': 'সম্পর্ক',
      'phone_number': 'ফোন নম্বর',
      'save_profile_continue': 'প্রোফাইল সংরক্ষণ করুন ও এগিয়ে যান',
      'skip_for_now': 'আপাতত এড়িয়ে যান',
      'profile_complete': 'প্রোফাইল প্রস্তুত',
      'ready_to_connect': 'আপনার জরুরি প্রোফাইল প্রস্তুত। আপনি এখন সাহারা অফলাইন মেশে যুক্ত।',
      'enter_sahara_home': 'সাহারা হোমে প্রবেশ করুন',
      'mesh_active': 'মেশ সক্রিয়',
      'mesh_inactive': 'মেশ নিষ্ক্রিয়',
      'battery': 'ব্যাটারি',
      'relays': 'রিলে',
      'peers_nearby': 'কাছাকাছি মানুষ',
      'emergency_sos': 'জরুরি এসওএস',
      'tap_sos_hint': 'জরুরি জীবন সংকটে ট্যাপ করুন',
      'sos_active': 'এসওএস সক্রিয়',
      'emergency_broadcast': 'জরুরি সম্প্রচার',
      'active_badge': '{count} সক্রিয়',
      'send_emergency_broadcast': 'জরুরি বার্তা সম্প্রচার করুন',
      'no_broadcasts': 'আপনার এলাকায় কোন জরুরি বার্তা নেই।',
      'comm_and_contacts': 'যোগাযোগ ও পরিচিতি',
      'messages': 'বার্তা',
      'conversations_count': '{count} কথোপকথন • স্টোর-অ্যান্ড-ফরোয়ার্ড সক্রিয়',
      'family': 'পরিবার',
      'family_reachable_count': '{reachable} / {total} মেশে সংযুক্ত',
      'nearby_people': 'কাছের মানুষ',
      'nearby_detected_count': '{count} জন মেশের আওতায় আছেন',
      'people_in_range': '{count} জন মেশ সীমানায় শনাক্ত',
      'search_nearby_hint': 'নাম, ফোন বা অবস্থান দিয়ে খুঁজুন...',
      'no_peers_found': '"{query}" এর সাথে কোন ব্যক্তি মেলেনি',
      'reachable': 'সংযুক্ত',
      'unreachable': 'সংযোগহীন',
      'direct': 'সরাসরি',
      'hops': '{count} হপ',
      'hop': '1 হপ',
      'ping': 'পিং করুন',
      'ping_sent_to': '{name} কে পিং পাঠানো হয়েছে',
      'message': 'বার্তা',
      'add_to_family': 'পরিবারে যুক্ত করুন',
      'added_to_family': '{name} কে পরিবারে যুক্ত করা হয়েছে',
      'broadcast_severity': 'বার্তার গুরুত্ব স্তর',
      'severity_advisory': 'পরামর্শ',
      'severity_warning': 'সতর্কবার্তা',
      'severity_evacuation': 'স্থানান্তর',
      'quick_suggestions': 'দ্রুত বার্তা (যোগ করতে ট্যাপ করুন)',
      'broadcast_message': 'বার্তা সম্প্রচার করুন',
      'enter_broadcast_hint': 'জরুরি বার্তা লিখুন...',
      'broadcast_button': 'বার্তা সম্প্রচার করুন',
      'broadcast_sent': 'বার্তা সম্প্রচারিত হয়েছে',
      'recipients_reached': 'প্রাপকদের কাছে পৌঁছেছে',
      'relays_count': 'রিলে',
      'compose_another': 'আরেকটি বার্তা লিখুন',
      'return_to_home': 'হোম পেজে ফিরুন',
      'cancel_sos': 'এসওএস বাতিল করুন',
      'hold_for_sos': 'এসওএস পাঠাতে ৩ সেকেন্ড চেপে রাখুন',
      'distress_beacon_active': 'বিপদ সংকেত সম্প্রচার করা হচ্ছে',
      'sos_broadcast_notice': 'সকল রিলেতে জরুরি এসওএস সক্রিয়',
      'ping_all_family': 'পরিবারের সকলকে পিং করুন',
      'add_family_member': 'পরিবারের সদস্য যুক্ত করুন',
      'emergency_messages': 'জরুরি বার্তা',
      'p2p_notice': 'P2P স্টোর-অ্যান্ড-ফরোয়ার্ড মেশ সক্রিয় • অফলাইন',
      'search': 'অনুসন্ধান',
      'cancel': 'বাতিল',
      'save': 'সংরক্ষণ',
    },

    // -------------------------------------------------------------
    // ASSAMESE (as)
    // -------------------------------------------------------------
    'as': {
      'tagline': 'অফলাইন জৰুৰীকালীন মেছ নেটৱৰ্ক',
      'welcome_desc': 'বানপানী আৰু ঘূৰ্ণীবতাহৰ সময়ত চেলুলাৰ নেটৱৰ্ক অবিহনেও পোনপটীয়া যোগাযোগ।',
      'get_started': 'আৰম্ভ কৰক',
      'already_configured': 'ইতিপূৰ্বে সজোৱা আছে? হোম চাওক',
      'select_language': 'আপোনাৰ ভাষা বাছক',
      'language_preference': 'ভাষাৰ পছন্দ',
      'disaster_coverage_desc': 'অসম, ওড়িশা, বিহাৰ, পশ্চিমবংগ, কেৰেলা, গুজৰাট আৰু উপকূলীয় অঞ্চলৰ বাবে।',
      'continue_btn': 'আগলৈ যাওক',
      'your_details': 'আপোনাৰ তথ্য',
      'personal_info': 'ব্যক্তিগত তথ্য',
      'gov_id_hint': 'চৰকাৰী পৰিচয় পত্ৰ (আধাৰ / ভোটাৰ আই ডি) অনুসৰি তথ্য দিয়ক।',
      'take_photo': 'ফটো তোলক',
      'choose_gallery': 'গেলেৰীৰ পৰা বাছক',
      'select_profile_photo': 'প্ৰফাইল ফটো বাছক',
      'change_photo': 'ফটো সলনি কৰক',
      'add_photo': 'ফটো যোগ কৰক',
      'full_name': 'সম্পূৰ্ণ নাম (চৰকাৰী পৰিচয় অনুসৰি)',
      'name_hint': 'যেনে: ৰাহুল শৰ্মা',
      'name_req': 'অনুগ্ৰহ কৰি আপোনাৰ সম্পূৰ্ণ নাম দিয়ক',
      'contact_number': 'মবাইল / যোগাযোগ নম্বৰ',
      'phone_hint': 'যেনে: +91 98765 43210',
      'phone_req': 'অনুগ্ৰহ কৰি যোগাযোগ নম্বৰ দিয়ক',
      'date_of_birth': 'জন্ম তাৰিখ',
      'dob_req': 'অনুগ্ৰহ কৰি জন্ম তাৰিখ দিয়ক',
      'dob_invalid': 'DD/MM/YYYY ধৰণত শুদ্ধ তাৰিখ দিয়ক',
      'current_location': 'বৰ্তমান স্থান',
      'use_current_location': 'বৰ্তমান স্থান ব্যৱহাৰ কৰক',
      'location_hint': 'যেনে: শিবিৰ ৩, গুৱাহাটী',
      'location_req': 'আপোনাৰ বৰ্তমান স্থান উল্লেখ কৰক',
      'acquiring_location': 'প্ৰকৃত জিপিএছ স্থান লোৱা হৈছে...',
      'location_services_disabled': 'স্থান সেৱা বন্ধ আছে। অনুগ্ৰহ কৰি GPS অন কৰক।',
      'location_permission_denied': 'স্থান অনুমতি অগ্ৰাহ্য কৰা হৈছে।',
      'location_permission_denied_forever': 'স্থান অনুমতি স্থায়ীভাৱে বন্ধ।',
      'emergency_contacts': 'জৰুৰীকালীন যোগাযোগ',
      'add_trusted_contacts': 'বিশ্বস্ত যোগাযোগ যোগ কৰক',
      'contacts_desc': 'বিপদৰ সময়ত জনাবলৈ কমেও এজন পৰিয়ালৰ সদস্য বা জৰুৰীকালীন সম্পৰ্ক যোগ কৰক।',
      'add_contact': 'যোগাযোগ যোগ কৰক',
      'contact_name': 'ব্যক্তিৰ নাম',
      'relationship': 'সম্পৰ্ক',
      'phone_number': 'ফোন নম্বৰ',
      'save_profile_continue': 'প্ৰফাইল সংৰক্ষণ কৰক আৰু আগবাঢ়ক',
      'skip_for_now': 'বৰ্তমানলৈ বাদ দিয়ক',
      'profile_complete': 'প্ৰফাইল সম্পূৰ্ণ হ\'ল',
      'ready_to_connect': 'আপোনাৰ জৰুৰী প্ৰফাইল সাজু। আপুনি এতিয়া ছাহাৰা অফলাইন মেছত উপলব্ধ।',
      'enter_sahara_home': 'ছাহাৰা হোমলৈ যাওক',
      'mesh_active': 'মেছ সক্ৰিয়',
      'mesh_inactive': 'মেছ নিষ্ক্ৰিয়',
      'battery': 'বেটাৰী',
      'relays': 'ৰিলে',
      'peers_nearby': 'ওচৰৰ লোক',
      'emergency_sos': 'জৰুৰীকালীন এছঅ\'এছ',
      'tap_sos_hint': 'জীৱনৰ বিপদ হ\'লে টিপক',
      'sos_active': 'এছঅ\'এছ সক্ৰিয়',
      'emergency_broadcast': 'জৰুৰীকালীন সম্প্ৰচাৰ',
      'active_badge': '{count} সক্ৰিয়',
      'send_emergency_broadcast': 'জৰুৰীকালীন বাৰ্তা প্ৰেৰণ কৰক',
      'no_broadcasts': 'আপোনাৰ অঞ্চলত কোনো জৰুৰী বাৰ্তা নাই।',
      'comm_and_contacts': 'যোগাযোগ আৰু সম্পৰ্ক',
      'messages': 'বাৰ্তা',
      'conversations_count': '{count} কথোপকথন • ষ্টোৰ-এণ্ড-ফৰৱাৰ্ড সক্ৰিয়',
      'family': 'পৰিয়াল',
      'family_reachable_count': '{reachable} / {total} মেছত উপলব্ধ',
      'nearby_people': 'ওচৰৰ লোক',
      'nearby_detected_count': '{count} জন মেছৰ পৰিসৰত আছে',
      'people_in_range': '{count} জন লোক মেছ পৰিসৰত পোৱা গৈছে',
      'search_nearby_hint': 'নাম, ফোন বা স্থান অনুসৰি সন্ধান কৰক...',
      'no_peers_found': '"{query}" ৰ সৈতে কোনো ব্যক্তি পোৱা নগল',
      'reachable': 'উপলব্ধ',
      'unreachable': 'অনুপলব্ধ',
      'direct': 'পোনপটীয়া',
      'hops': '{count} হপ',
      'hop': '1 হপ',
      'ping': 'পিং কৰক',
      'ping_sent_to': '{name} লৈ পিং পঠোৱা হ\'ল',
      'message': 'বাৰ্তা',
      'add_to_family': 'পৰিয়ালত যোগ কৰক',
      'added_to_family': '{name} ক পৰিয়ালত যোগ কৰা হ\'ল',
      'broadcast_severity': 'বাৰ্তাৰ গুৰুত্ব',
      'severity_advisory': 'পৰামৰ্শ',
      'severity_warning': 'সতৰ্কবাৰ্তা',
      'severity_evacuation': 'স্থানান্তৰ',
      'quick_suggestions': 'দ্ৰুত পৰামৰ্শ (টিপক)',
      'broadcast_message': 'বাৰ্তা সম্প্ৰচাৰ কৰক',
      'enter_broadcast_hint': 'জৰুৰী বাৰ্তা লিখক...',
      'broadcast_button': 'বাৰ্তা সম্প্ৰচাৰ কৰক',
      'broadcast_sent': 'বাৰ্তা প্ৰেৰণ কৰা হ\'ল',
      'recipients_reached': 'প্ৰাপ্তকৰ্তাৰ কাষ পালে',
      'relays_count': 'ৰিলে',
      'compose_another': 'আন এটা বাৰ্তা লিখক',
      'return_to_home': 'মুখ্য পৃষ্ঠালৈ উভতি যাওক',
      'cancel_sos': 'এছঅ\'এছ বাতিল কৰক',
      'hold_for_sos': 'এছঅ\'এছৰ বাবে ৩ ছেকেণ্ড ধৰি ৰাখক',
      'distress_beacon_active': 'সংকট সংকেত সম্প্ৰচাৰ হৈ আছে',
      'sos_broadcast_notice': 'সকলো ৰিলেত জৰুৰী এছঅ\'এছ সক্ৰিয়',
      'ping_all_family': 'সমগ্ৰ পৰিয়ালক পিং কৰক',
      'add_family_member': 'পৰিয়ালৰ সদস্য যোগ কৰক',
      'emergency_messages': 'জৰুৰী বাৰ্তা',
      'p2p_notice': 'P2P অফলাইন মেছ সক্ৰিয়',
      'search': 'সন্ধান কৰক',
      'cancel': 'বাতিল',
      'save': 'সংৰক্ষণ',
    },

    // -------------------------------------------------------------
    // MALAYALAM (ml)
    // -------------------------------------------------------------
    'ml': {
      'tagline': 'ഓഫ്‌ലൈൻ എമർജൻസി മെഷ് നെറ്റ്‌വർക്ക്',
      'welcome_desc': 'പ്രളയത്തിലും ചുഴലിക്കാറ്റിലും ടവറുകൾ തകരാറിലാകുമ്പോൾ പ്രവർത്തിക്കുന്ന ഓഫ്‌ലൈൻ ആശയവിനിമയം.',
      'get_started': 'ആരംഭിക്കുക',
      'already_configured': 'നേരത്തെ ക്രമീകരിച്ചിട്ടുണ്ടോ? ഹോമിലേക്ക് പോവുക',
      'select_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'language_preference': 'ഭാഷ മുൻഗണന',
      'disaster_coverage_desc': 'കേരളം, അസം, ഒഡീഷ, ബിഹാർ, ബംഗാൾ, ഗുജറാത്ത് തീരദേശ ദുരന്ത മേഖലകൾക്കായുള്ള കവറേജ്.',
      'continue_btn': 'തുടരുക',
      'your_details': 'നിങ്ങളുടെ വിവരങ്ങൾ',
      'personal_info': 'വ്യക്തിഗത വിവരങ്ങൾ',
      'gov_id_hint': 'ഔദ്യോഗിക തിരിച്ചറിയൽ രേഖയിലെ (ആധാർ / വോട്ടർ ഐഡി) വിവരങ്ങൾ നൽകുക.',
      'take_photo': 'ഫോട്ടോ എടുക്കുക',
      'choose_gallery': 'ഗാലറിയിൽ നിന്ന് തിരഞ്ഞെടുക്കുക',
      'select_profile_photo': 'പ്രൊഫൈൽ ഫോട്ടോ തിരഞ്ഞെടുക്കുക',
      'change_photo': 'ഫോട്ടോ മാറ്റുക',
      'add_photo': 'ഫോട്ടോ ചേർക്കുക',
      'full_name': 'പൂർണ്ണ നാമം (ഐഡി കാർഡ് പ്രകാരം)',
      'name_hint': 'ഉദാ: രാഹുൽ ശർമ്മ',
      'name_req': 'ദയവായി നിങ്ങളുടെ ഔദ്യോഗിക പേര് നൽകുക',
      'contact_number': 'മൊബൈൽ നമ്പർ',
      'phone_hint': 'ഉദാ: +91 98765 43210',
      'phone_req': 'ദയവായി ഫോൺ നമ്പർ നൽകുക',
      'date_of_birth': 'ജനനത്തീയതി',
      'dob_req': 'ദയവായി ജനനത്തീയതി നൽകുക',
      'dob_invalid': 'DD/MM/YYYY ഫോർമാറ്റിൽ നൽകുക',
      'current_location': 'നിലവിലെ സ്ഥലം',
      'use_current_location': 'നിലവിലെ സ്ഥലം ഉപയോഗിക്കുക',
      'location_hint': 'ഉദാ: ക്യാമ്പ് 3, എറണാകുളം',
      'location_req': 'ദയവായി നിങ്ങളുടെ സ്ഥലം നൽകുക',
      'acquiring_location': 'യഥാർത്ഥ GPS സ്ഥാനം കണ്ടെത്തുന്നു...',
      'location_services_disabled': 'ലൊക്കേഷൻ ഓഫാണ്. ദയവായി GPS ഓൺ ചെയ്യുക.',
      'location_permission_denied': 'ലൊക്കേഷൻ അനുമതി നിരസിച്ചു.',
      'location_permission_denied_forever': 'ലൊക്കേഷൻ അനുമതി സ്ഥിരമായി നിരസിച്ചു.',
      'emergency_contacts': 'അടിയന്തര കോൺടാക്റ്റുകൾ',
      'add_trusted_contacts': 'വിശ്വസ്ത കോൺടാക്റ്റുകൾ ചേർക്കുക',
      'contacts_desc': 'ദുരന്ത സമയത്ത് വിവരമറിയിക്കാൻ ഒരു കുടുംബാംഗത്തെയോ അടിയന്തര കോൺടാക്റ്റോ ചേർക്കുക.',
      'add_contact': 'കോൺടാക്റ്റ് ചേർക്കുക',
      'contact_name': 'പേര്',
      'relationship': 'ബന്ധം',
      'phone_number': 'ഫോൺ നമ്പർ',
      'save_profile_continue': 'പ്രൊഫൈൽ സേവ് ചെയ്തു തുടരുക',
      'skip_for_now': 'ഇപ്പൊൾ ഒഴിവാക്കുക',
      'profile_complete': 'പ്രൊഫൈൽ പൂർത്തിയായി',
      'ready_to_connect': 'നിങ്ങളുടെ പ്രൊഫൈൽ തയ്യാറാണ്. സഹാറ മെഷ് നെറ്റ്‌വർക്കിൽ നിങ്ങൾ ലഭ്യമാണ്.',
      'enter_sahara_home': 'സഹാറ ഹോമിലേക്ക് പ്രവേശിക്കുക',
      'mesh_active': 'മെഷ് സജീവം',
      'mesh_inactive': 'മെഷ് നിർജ്ജീവം',
      'battery': 'ബാറ്ററി',
      'relays': 'റിലേകൾ',
      'peers_nearby': 'സമീപത്തുള്ളവർ',
      'emergency_sos': 'അടിയന്തര SOS',
      'tap_sos_hint': 'അപകടസാഹചര്യങ്ങളിൽ ടാപ്പ് ചെയ്യുക',
      'sos_active': 'SOS സജീവം',
      'emergency_broadcast': 'അടിയന്തര സന്ദേശം',
      'active_badge': '{count} സജീവം',
      'send_emergency_broadcast': 'അടിയന്തര സന്ദേശം അയക്കുക',
      'no_broadcasts': 'നിങ്ങളുടെ പ്രദേശത്ത് അറിയിപ്പുകൾ ഒന്നുമില്ല.',
      'comm_and_contacts': 'ആശയവിനിമയവും കോൺടാക്റ്റുകളും',
      'messages': 'സന്ദേശങ്ങൾ',
      'conversations_count': '{count} സംഭാഷണങ്ങൾ • ഓഫ്‌ലൈൻ മെഷ് സജീവം',
      'family': 'കുടുംബം',
      'family_reachable_count': '{reachable} / {total} പേരെ ബന്ധപ്പെടാം',
      'nearby_people': 'സമീപമുള്ള ആളുകൾ',
      'nearby_detected_count': '{count} പേർ മെഷ് പരിധിയിലുണ്ട്',
      'people_in_range': '{count} ആളുകളെ പരിധിയിൽ കണ്ടെത്തി',
      'search_nearby_hint': 'പേരോ നമ്പറോ സ്ഥലമോ തിരയുക...',
      'no_peers_found': '"{query}" അനുയോജ്യമായ ആളുകളെ കണ്ടെത്തിയില്ല',
      'reachable': 'ലഭ്യമാണ്',
      'unreachable': 'ലഭ്യമല്ല',
      'direct': 'നേരിട്ട്',
      'hops': '{count} ഹോപ്സ്',
      'hop': '1 ഹോപ്പ്',
      'ping': 'പിംഗ് ചെയ്യുക',
      'ping_sent_to': '{name} എന്നവർക്ക് പിംഗ് അയച്ചു',
      'message': 'സന്ദേശം',
      'add_to_family': 'കുടുംബത്തിൽ ചേർക്കുക',
      'added_to_family': '{name} നെ കുടുംബത്തിൽ ചേർത്തു',
      'broadcast_severity': 'തീവ്രത തരം',
      'severity_advisory': 'നിർദ്ദേശം',
      'severity_warning': 'മുന്നറിയിപ്പ്',
      'severity_evacuation': 'ഒഴിപ്പിക്കൽ',
      'quick_suggestions': 'പെട്ടെന്നുള്ള സന്ദേശങ്ങൾ',
      'broadcast_message': 'സന്ദേശം പ്രക്ഷേപണം ചെയ്യുക',
      'enter_broadcast_hint': 'അടിയന്തര സന്ദേശം രേഖപ്പെടുത്തുക...',
      'broadcast_button': 'സന്ദേശം അയക്കുക',
      'broadcast_sent': 'സന്ദേശം അയച്ചു',
      'recipients_reached': 'എത്തിച്ചേർന്ന ആളുകൾ',
      'relays_count': 'റിലേകൾ',
      'compose_another': 'മറ്റൊരു സന്ദേശം തയ്യാറാക്കുക',
      'return_to_home': 'ഹോമിലേക്ക് മടങ്ങുക',
      'cancel_sos': 'SOS റദ്ദാക്കുക',
      'hold_for_sos': 'SOS അയക്കാൻ 3 സെക്കൻഡ് അമർത്തിപ്പിടിക്കുക',
      'distress_beacon_active': 'അടിയന്തര സിഗ്നൽ പ്രക്ഷേപണം ചെയ്യുന്നു',
      'sos_broadcast_notice': 'എല്ലാ റിലേകളിലും അടിയന്തര SOS സജീവം',
      'ping_all_family': 'എല്ലാ കുടുംബാംഗങ്ങളെയും പിംഗ് ചെയ്യുക',
      'add_family_member': 'കുടുംബാംഗത്തെ ചേർക്കുക',
      'emergency_messages': 'അടിയന്തര സന്ദേശങ്ങൾ',
      'p2p_notice': 'ഓഫ്‌ലൈൻ P2P മെഷ് സജീവം',
      'search': 'തിരയുക',
      'cancel': 'റദ്ദാക്കുക',
      'save': 'സേവ് ചെയ്യുക',
    },

    // -------------------------------------------------------------
    // GUJARATI (gu)
    // -------------------------------------------------------------
    'gu': {
      'tagline': 'ઓફલાઇન ઇમરજન્સી મેશ નેટવર્ક',
      'welcome_desc': 'પૂર અને વાવાઝોડા વખતે મોબાઇલ ટાવર બંધ હોય ત્યારે સીધો સુરક્ષિત સંપર્ક.',
      'get_started': 'શરૂ કરો',
      'already_configured': 'પહેલેથી સેટઅપ છે? હોમ પર જાઓ',
      'select_language': 'તમારી ભાષા પસંદ કરો',
      'language_preference': 'ભાષાની પસંદગી',
      'disaster_coverage_desc': 'ગુજરાત, આસામ, ઓડિશા, બિહાર, બંગાળ, કેરળ અને દરિયાકાંઠાના વિસ્તારો માટે.',
      'continue_btn': 'આગળ વધો',
      'your_details': 'તમારી વિગતો',
      'personal_info': 'વ્યક્તિગત માહિતી',
      'gov_id_hint': 'સરકારી આઈડી (આધાર / મતદાર કાર્ડ) મુજબ વિગતો ભરો.',
      'take_photo': 'ફોટો પાડો',
      'choose_gallery': 'ગેલેરીમાંથી પસંદ કરો',
      'select_profile_photo': 'પ્રોફાઇલ ફોટો પસંદ કરો',
      'change_photo': 'ફોટો બદલો',
      'add_photo': 'ફોટો ઉમેરો',
      'full_name': 'પૂરું નામ (સરકારી આઈડી મુજબ)',
      'name_hint': 'દા.ત. રાહુલ શર્મા',
      'name_req': 'કૃપા કરીને તમારું સત્તાવાર નામ લખો',
      'contact_number': 'મોબાઇલ / સંપર્ક નંબર',
      'phone_hint': 'દા.ત. +91 98765 43210',
      'phone_req': 'કૃપા કરીને સંપર્ક નંબર લખો',
      'date_of_birth': 'જન્મ તારીખ',
      'dob_req': 'કૃપા કરીને જન્મ તારીખ લખો',
      'dob_invalid': 'DD/MM/YYYY ફોર્મેટમાં તારીખ લખો',
      'current_location': 'હાલનું સ્થળ',
      'use_current_location': 'હાલના સ્થળનો ઉપયોગ કરો',
      'location_hint': 'દા.ત. રાહત કેમ્પ ૩, સુરત',
      'location_req': 'કૃપા કરીને તમારું સ્થળ દાખલ કરો',
      'acquiring_location': 'વાસ્તવિક જીપીએસ સ્થાન મેળવી રહ્યું છે...',
      'location_services_disabled': 'સ્થાન સેવાઓ બંધ છે. કૃપા કરીને GPS ચાલુ કરો.',
      'location_permission_denied': 'સ્થાન પરવાનગી નકારી.',
      'location_permission_denied_forever': 'સ્થાન પરવાનગી કાયમી ધોરણે નકારી.',
      'emergency_contacts': 'ઇમરજન્સી સંપર્કો',
      'add_trusted_contacts': 'વિશ્વાસુ સંપર્કો ઉમેરો',
      'contacts_desc': 'આપત્તિ સમયે જાણ કરવા માટે ઓછામાં ઓછો એક પરિવારનો સભ્ય ઉમેરો.',
      'add_contact': 'સંપર્ક ઉમેરો',
      'contact_name': 'સંપર્કનું નામ',
      'relationship': 'સંબંધ',
      'phone_number': 'ફોન નંબર',
      'save_profile_continue': 'પ્રોફાઇલ સાચવો અને આગળ વધો',
      'skip_for_now': 'હમણાં માટે રહેવા દો',
      'profile_complete': 'પ્રોફાઇલ સેટઅપ પૂર્ણ',
      'ready_to_connect': 'તમારી પ્રોફાઇલ તૈયાર છે. હવે તમે સહારા ઓફલાઇન મેશ પર ઉપલબ્ધ છો.',
      'enter_sahara_home': 'સહારા હોમમાં પ્રવેશ કરો',
      'mesh_active': 'મેશ સક્રિય',
      'mesh_inactive': 'મેશ નિષ્ક્રિય',
      'battery': 'બેટરી',
      'relays': 'રીલે',
      'peers_nearby': 'નજીકના સંપર્કો',
      'emergency_sos': 'ઇમરજન્સી SOS',
      'tap_sos_hint': 'જીવન જોખમમાં હોય ત્યારે દબાવો',
      'sos_active': 'SOS સક્રિય',
      'emergency_broadcast': 'ઇમરજન્સી બ્રોડકાસ્ટ',
      'active_badge': '{count} સક્રિય',
      'send_emergency_broadcast': 'ઇમરજન્સી સંદેશ મોકલો',
      'no_broadcasts': 'તમારા વિસ્તારમાં કોઈ ઇમરજન્સી સંદેશ નથી.',
      'comm_and_contacts': 'સંચાર અને સંપર્કો',
      'messages': 'સંદેશાઓ',
      'conversations_count': '{count} વાતચીત • સ્ટોર-એન્ડ-ફોરવર્ડ સક્રિય',
      'family': 'પરિવાર',
      'family_reachable_count': '{reachable} / {total} મેશ પર સંપર્કમાં',
      'nearby_people': 'નજીકના લોકો',
      'nearby_detected_count': '{count} લોકો રેન્જમાં છે',
      'people_in_range': '{count} લોકો રેન્જમાં મળ્યા',
      'search_nearby_hint': 'નામ, ફોન કે સ્થળ દ્વારા શોધો...',
      'no_peers_found': '"{query}" માટે કોઈ વ્યક્તિ મળ્યા નથી',
      'reachable': 'સંપર્કમાં',
      'unreachable': 'સંપર્ક બહાર',
      'direct': 'સીધો',
      'hops': '{count} હોપ્સ',
      'hop': '1 હોપ',
      'ping': 'પિંગ કરો',
      'ping_sent_to': '{name} ને પિંગ મોકલ્યો',
      'message': 'સંદેશ',
      'add_to_family': 'પરિવારમાં ઉમેરો',
      'added_to_family': '{name} ને પરિવારમાં ઉમેર્યા',
      'broadcast_severity': 'સંદેશ ગંભીરતા',
      'severity_advisory': 'સલાહ',
      'severity_warning': 'ચેતવણી',
      'severity_evacuation': 'સ્થળાંતર',
      'quick_suggestions': 'ઝડપી સંદેશાઓ',
      'broadcast_message': 'સંદેશ પ્રસારિત કરો',
      'enter_broadcast_hint': 'ઇમરજન્સી સંદેશ લખો...',
      'broadcast_button': 'સંદેશ મોકલો',
      'broadcast_sent': 'સંદેશ મોકલાઈ ગયો',
      'recipients_reached': 'મળેલા લોકો',
      'relays_count': 'રીલે',
      'compose_another': 'બીજો સંદેશ લખો',
      'return_to_home': 'હોમ પર પાછા જાઓ',
      'cancel_sos': 'SOS રદ કરો',
      'hold_for_sos': 'SOS મોકલવા 3 સેકન્ડ દબાવી રાખો',
      'distress_beacon_active': 'સંકટ સંકેત પ્રસારિત થઈ રહ્યો છે',
      'sos_broadcast_notice': 'બધા રીલે પર ઇમરજન્સી SOS સક્રિય',
      'ping_all_family': 'બધા પરિવારજનોને પિંગ કરો',
      'add_family_member': 'પરિવારનો સભ્ય ઉમેરો',
      'emergency_messages': 'ઇમરજન્સી સંદેશાઓ',
      'p2p_notice': 'P2P ઓફલાઇન મેશ નેટવર્ક સક્રિય',
      'search': 'શોધો',
      'cancel': 'રદ કરો',
      'save': 'સાચવો',
    },

    // -------------------------------------------------------------
    // MAITHILI (mai)
    // -------------------------------------------------------------
    'mai': {
      'tagline': 'ऑफलाइन आपातकालीन मेश नेटवर्क',
      'welcome_desc': 'बाढ़ि आ चक्रवात काल में सेलुलर नेटवर्क बिना सीधा संवाद।',
      'get_started': 'शुरू करू',
      'already_configured': 'पहिने सँ कॉन्फ़िगर अछि? होम पर जाऊ',
      'select_language': 'अपन भाषा चुनू',
      'language_preference': 'भाषा प्राथमिकता',
      'disaster_coverage_desc': 'असम, ओडिशा, बिहार, पश्चिम बंगाल, केरल, गुजरात आ तटीय क्षेत्रक लेल।',
      'continue_btn': 'आगाँ बढ़ू',
      'your_details': 'अहाँक विवरण',
      'personal_info': 'व्यक्तिगत जानकारी',
      'gov_id_hint': 'सरकारी पहचान पत्र (आधार / वोटर कार्ड) अनुसार विवरण भरू।',
      'take_photo': 'फोटो खींचू',
      'choose_gallery': 'गैलरी सँ चुनू',
      'select_profile_photo': 'प्रोफ़ाइल फोटो चुनू',
      'change_photo': 'फोटो बदलू',
      'add_photo': 'फोटो जोड़ू',
      'full_name': 'पूरा नाम (सरकारी पहचान पत्रक अनुसार)',
      'name_hint': 'उदा. राहुल शर्मा',
      'name_req': 'कृपा क\' अपन पूरा नाम भरू',
      'contact_number': 'मोबाइल / संपर्क नंबर',
      'phone_hint': 'उदा. +91 98765 43210',
      'phone_req': 'कृपा क\' अपन फ़ोन नंबर भरू',
      'date_of_birth': 'जन्म तिथि',
      'dob_req': 'कृपा क\' जन्म तिथि भरू',
      'dob_invalid': 'DD/MM/YYYY प्रारूप में सही तिथि भरू',
      'current_location': 'वर्तमान स्थान',
      'use_current_location': 'वर्तमान स्थानक उपयोग करू',
      'location_hint': 'उदा. शरण स्थल ३, दरभंगा',
      'location_req': 'अपन वर्तमान स्थानक विवरण दिअ',
      'acquiring_location': 'जीपीएस स्थान प्राप्त भ\' रहल अछि...',
      'location_services_disabled': 'स्थान सेवा बंद अछि। GPS चालू करू।',
      'location_permission_denied': 'स्थान अनुमति अस्वीकृत।',
      'location_permission_denied_forever': 'स्थान अनुमति स्थायी रूप सँ बंद।',
      'emergency_contacts': 'आपातकालीन संपर्क',
      'add_trusted_contacts': 'विश्वसनीय संपर्क जोड़ू',
      'contacts_desc': 'आपदाक समय में सूचित करय लेल कम सँ कम एकटा परिवारक सदस्य जोड़ू।',
      'add_contact': 'संपर्क जोड़ू',
      'contact_name': 'संपर्कक नाम',
      'relationship': 'संबंध',
      'phone_number': 'फोन नंबर',
      'save_profile_continue': 'प्रोफ़ाइल सुरक्षित करू आ आगाँ बढ़ू',
      'skip_for_now': 'एखन छोड़ू',
      'profile_complete': 'प्रोफ़ाइल सेटअप पूर्ण',
      'ready_to_connect': 'अहाँक प्रोफ़ाइल तैयार अछि। अहाँ सहारा ऑफलाइन मेश पर उपलब्ध छी।',
      'enter_sahara_home': 'सहारा होम में प्रवेश करू',
      'mesh_active': 'मेश सक्रिय',
      'mesh_inactive': 'मेश निष्क्रिय',
      'battery': 'बैटरी',
      'relays': 'रिले',
      'peers_nearby': 'निकटक लोक',
      'emergency_sos': 'आपातकालीन एसओएस',
      'tap_sos_hint': 'जीवन संकट काल में दबाउ',
      'sos_active': 'एसओएस सक्रिय',
      'emergency_broadcast': 'आपातकालीन प्रसारण',
      'active_badge': '{count} सक्रिय',
      'send_emergency_broadcast': 'आपातकालीन प्रसारण पठाउ',
      'no_broadcasts': 'अहाँक क्षेत्र में कोनो आपातकालीन प्रसारण नहि अछि।',
      'comm_and_contacts': 'संचार आ संपर्क',
      'messages': 'संदेश',
      'conversations_count': '{count} बातचीत • स्टोर-एंड-फॉरवर्ड सक्रिय',
      'family': 'परिवार',
      'family_reachable_count': '{reachable} / {total} मेश पर संपर्क योग्य',
      'nearby_people': 'आस-पासक लोक',
      'nearby_detected_count': '{count} गोटा मेश सीमा में छथि',
      'people_in_range': '{count} गोटा मेश सीमा में भेटल',
      'search_nearby_hint': 'नाम, फोन वा स्थान सँ खोजू...',
      'no_peers_found': '"{query}" सँ मेल खाइत कोनो व्यक्ति नहि भेटल',
      'reachable': 'पहुंच योग्य',
      'unreachable': 'पहुंच सँ बाहर',
      'direct': 'सीधा',
      'hops': '{count} हॉप',
      'hop': '1 हॉप',
      'ping': 'पिंग करू',
      'ping_sent_to': '{name} केँ पिंग पठाओल गेल',
      'message': 'संदेश',
      'add_to_family': 'परिवार में जोड़ू',
      'added_to_family': '{name} केँ परिवार में जोड़ल गेल',
      'broadcast_severity': 'प्रसारणक गंभीरता',
      'severity_advisory': 'परामर्श',
      'severity_warning': 'चेतावनी',
      'severity_evacuation': 'निकासी',
      'quick_suggestions': 'त्वरित सुझाव',
      'broadcast_message': 'संदेश प्रसारित करू',
      'enter_broadcast_hint': 'आपातकालीन संदेश लिखू...',
      'broadcast_button': 'संदेश प्रसारित करू',
      'broadcast_sent': 'प्रसारण पठाओल गेल',
      'recipients_reached': 'प्राप्तकर्ता धरि पहुँचल',
      'relays_count': 'रिले',
      'compose_another': 'आन संदेश लिखू',
      'return_to_home': 'मुख्य पृष्ठ पर घुरु',
      'cancel_sos': 'एसओएस रद्द करू',
      'hold_for_sos': 'एसओएस लेल ३ सेकंड दबा क राखू',
      'distress_beacon_active': 'संकट संकेत प्रसारित भ\' रहल अछि',
      'sos_broadcast_notice': 'सभ रिले पर आपातकालीन एसओएस सक्रिय',
      'ping_all_family': 'सभ परिवारक लोक के पिंग करू',
      'add_family_member': 'परिवारक सदस्य जोड़ू',
      'emergency_messages': 'आपातकालीन संदेश',
      'p2p_notice': 'P2P ऑफलाइन मेश सक्रिय',
      'search': 'खोजू',
      'cancel': 'रद्द करू',
      'save': 'सुरक्षित करू',
    },

    // -------------------------------------------------------------
    // BODO (brx)
    // -------------------------------------------------------------
    'brx': {
      'tagline': 'अफलाइन आपतकालीन मेश नेटवर्क',
      'welcome_desc': 'दैबाना आरो बारहुंखायाव नेटवर्क गैयाब्लाबो सोमोन्दो लाखिनो हानाय राहा।',
      'get_started': 'जागाय',
      'already_configured': 'सिगांनो खालामबाय? नआव थां',
      'select_language': 'गावनि रावखौ सायख',
      'language_preference': 'राव सायखनाय',
      'disaster_coverage_desc': 'आसाम, ओडिशा, बिहार, पश्चिम बंगाल, केरला आरो गुजरात ओनसोलफोरनि थाखाय।',
      'continue_btn': 'थांगासिनो था',
      'your_details': 'नोंनि फोरमायथि',
      'personal_info': 'गावनि खौरां',
      'gov_id_hint': 'सोरखारि आइदि (आधार / भोटार कार्ड) बादियै लिर।',
      'take_photo': 'फोटो ला',
      'choose_gallery': 'गेलारिफ्राय सायख',
      'select_profile_photo': 'प्रफाइल फोटो सायख',
      'change_photo': 'फोटो सोलाय',
      'add_photo': 'फोटो दाजाब',
      'full_name': 'गासै मुं (सोरखारि आइदि बादियै)',
      'name_hint': 'उदा. राहुल शर्मा',
      'name_req': 'अननानै गावनि सोरखारि मुं लिर',
      'contact_number': 'मबाइल / सोमोन्दो नम्बर',
      'phone_hint': 'उदा. +91 98765 43210',
      'phone_req': 'अननानै मबाइल नम्बर लिर',
      'date_of_birth': 'जोनों सान',
      'dob_req': 'अननानै जोनों सान लिर',
      'dob_invalid': 'DD/MM/YYYY बादियै सान लिर',
      'current_location': 'दासान्दि जायगा',
      'use_current_location': 'दासान्दि जायगा बाहाय',
      'location_hint': 'उदा. शेल्टर ३, गुवाहाटी',
      'location_req': 'अननानै नोंनि जायगानि मुं लिर',
      'acquiring_location': 'GPS जायगा नागिरगासिनो दं...',
      'location_services_disabled': 'जायगा सेवा बन्द दं। GPS अन खालाम।',
      'location_permission_denied': 'जायगा अनसुंथाइ गैया।',
      'location_permission_denied_forever': 'जायगा अनसुंथाइ जोबथा बन्द जाबाय।',
      'emergency_contacts': 'आपतकालीन सोमोन्दो',
      'add_trusted_contacts': 'फोथायथाव सोमोन्दो दाजाब',
      'contacts_desc': 'आपतनि समाव खौरां हरनो खमसेखम सासे नख\'रनि सुबुं दाजाब।',
      'add_contact': 'सोमोन्दो दाजाब',
      'contact_name': 'सुबुं मुं',
      'relationship': 'सोमोन्दो',
      'phone_number': 'फन नम्बर',
      'save_profile_continue': 'प्रफाइल थिनानै थांगासिनो था',
      'skip_for_now': 'दानिफ्राय गारथ\'',
      'profile_complete': 'प्रफाइल जोबबाय',
      'ready_to_connect': 'नोंनि आपत प्रफाइल थियारि। नों सहारा मेशाव मोननो हाबाय।',
      'enter_sahara_home': 'सहारा नआव हाब',
      'mesh_active': 'मेश खामानि मावगासिनो',
      'mesh_inactive': 'मेश बन्द',
      'battery': 'बेटारी',
      'relays': 'रिले',
      'peers_nearby': 'खाथिनि सुबुं',
      'emergency_sos': 'आपतकालीन SOS',
      'tap_sos_hint': 'जिउनि आपत समाव थु',
      'sos_active': 'SOS मावगासिनो',
      'emergency_broadcast': 'आपतकालीन फोसावनाय',
      'active_badge': '{count} मावगासिनो',
      'send_emergency_broadcast': 'आपतकालीन फोसावनाय हर',
      'no_broadcasts': 'नोंनि ओनसोलआव आपतकालीन फोसावनाय गैया।',
      'comm_and_contacts': 'सोमोन्दो आरो खौरां',
      'messages': 'खौरां',
      'conversations_count': '{count} रायलायनाय • स्टोर-एण्ड-फरवार्ड सलिगासिनो',
      'family': 'नख\'र',
      'family_reachable_count': '{reachable} / {total} मेशाव सोमोन्दो दं',
      'nearby_people': 'खाथिनि सुबुं',
      'nearby_detected_count': '{count} सुबुं मेश सिमाव दं',
      'people_in_range': '{count} सिमाव मोननाय सुबुं',
      'search_nearby_hint': 'मुं, फन एबा जायगानि गेजेरजों नागिर...',
      'no_peers_found': '"{query}" जों गोरोबनाय सुबुं मोनाखै',
      'reachable': 'सोमोन्दो हानाय',
      'unreachable': 'सोमोन्दो गैयि',
      'direct': 'थोंजों',
      'hops': '{count} हप',
      'hop': '1 हप',
      'ping': 'पिं हर',
      'ping_sent_to': '{name} नो पिं हरबाय',
      'message': 'खौरां',
      'add_to_family': 'नख\'राव दाजाब',
      'added_to_family': '{name} खौ नख\'राव दाजाबबाय',
      'broadcast_severity': 'फोसावनायनि गोनांथि',
      'severity_advisory': 'बुंथि',
      'severity_warning': 'हुसियार',
      'severity_evacuation': 'उदां खालामनाय',
      'quick_suggestions': 'गोख्रै बाथ्रा (थुनानै लिर)',
      'broadcast_message': 'खौरां फोसाव',
      'enter_broadcast_hint': 'आपतकालीन खौरां लिर...',
      'broadcast_button': 'खौरां फोसाव',
      'broadcast_sent': 'फोसावनाय दैथायबाय',
      'recipients_reached': 'मोननाय सुबुं',
      'relays_count': 'रिले',
      'compose_another': 'गुबुन खौरां लिर',
      'return_to_home': 'हमाव थांफिन',
      'cancel_sos': 'SOS दानखार',
      'hold_for_sos': 'SOS थाखाय ३ सेकेन्द हमना लाखि',
      'distress_beacon_active': 'आपत संकेत फोसावगासिनो दं',
      'sos_broadcast_notice': 'गासै रिलेयाव आपतकालीन SOS मावगासिनो',
      'ping_all_family': 'गासै नख\'रखौ पिं हर',
      'add_family_member': 'नख\'रनि सुबुं दाजाब',
      'emergency_messages': 'आपतकालीन खौरां',
      'p2p_notice': 'P2P अफलाइन मेश सलिगासिनो',
      'search': 'नागिर',
      'cancel': 'दानखार',
      'save': 'थिना लाखि',
    },

    // -------------------------------------------------------------
    // TELUGU (te)
    // -------------------------------------------------------------
    'te': {
      'tagline': 'ఆఫ్‌లైన్ ఎమర్జెన్సీ మెష్ నెట్‌వర్క్',
      'welcome_desc': 'వరదలు మరియు తుఫానుల సమయంలో సెల్ టవర్లు పనిచేయకపోయినా నేరుగా పనిచేసే కమ్యూనికేషన్.',
      'get_started': 'ప్రారంభించండి',
      'already_configured': 'ఇప్పటికే సెటప్ చేశారా? హోమ్‌కు వెళ్లండి',
      'select_language': 'మీ భాషను ఎంచుకోండి',
      'language_preference': 'భాష ప్రాధాన్యత',
      'disaster_coverage_desc': 'తీరప్రాంత తుఫాను మండలాలు, ఒడిశా, కేరళ, గుజరాత్ తదితర విపత్తు ప్రాంతాలకు అనుకూలం.',
      'continue_btn': 'కొనసాగించండి',
      'your_details': 'మీ వివరాలు',
      'personal_info': 'వ్యక్తిగత సమాచారం',
      'gov_id_hint': 'ప్రభుత్వ గుర్తింపు కార్డు (ఆధార్ / ఓటర్ ఐడీ) ప్రకారం వివరాలు నమోదు చేయండి.',
      'take_photo': 'ఫోటో తీయండి',
      'choose_gallery': 'గ్యాలరీ నుండి ఎంచుకోండి',
      'select_profile_photo': 'ప్రొఫైల్ ఫోటోను ఎంచుకోండి',
      'change_photo': 'ఫోటో మార్చండి',
      'add_photo': 'ఫోటో జోడించండి',
      'full_name': 'పూర్తి పేరు (ప్రభుత్వ ఐడీ ప్రకారం)',
      'name_hint': 'ఉదా: రాహుల్ శర్మ',
      'name_req': 'దయచేసి మీ పూర్తి అధికారిక పేరు నమోదు చేయండి',
      'contact_number': 'మొబైల్ / సంప్రదింపు సంఖ్య',
      'phone_hint': 'ఉదా: +91 98765 43210',
      'phone_req': 'దయచేసి మీ ఫోన్ నంబర్ నమోదు చేయండి',
      'date_of_birth': 'పుట్టిన తేదీ',
      'dob_req': 'దయచేసి మీ పుట్టిన తేదీని నమోదు చేయండి',
      'dob_invalid': 'DD/MM/YYYY ఫార్మాట్‌లో సరైన తేదీని ఇవ్వండి',
      'current_location': 'ప్రస్తుత స్థానం',
      'use_current_location': 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
      'location_hint': 'ఉదా: షెల్టర్ 3, విశాఖపట్నం',
      'location_req': 'దయచేసి మీ ప్రస్తుత స్థానాన్ని నమోదు చేయండి',
      'acquiring_location': 'నిజమైన GPS స్థానాన్ని పొందుతోంది...',
      'location_services_disabled': 'లొకేషన్ సేవలు నిలిపివేయబడ్డాయి. దయచేసి GPS ఆన్ చేయండి.',
      'location_permission_denied': 'లొకేషన్ అనుమతి నిరాకరించబడింది.',
      'location_permission_denied_forever': 'లొకేషన్ అనుమతి శాశ్వతంగా నిరాకరించబడింది.',
      'emergency_contacts': 'అత్యవసర పరిచయాలు',
      'add_trusted_contacts': 'విశ్వసనీయ పరిచయాలను జోడించండి',
      'contacts_desc': 'విపత్తు సమయంలో సమాచారం ఇవ్వడానికి కనీసం ఒక కుటుంబ సభ్యుడిని లేదా అత్యవసర పరిచయాన్ని జోడించండి.',
      'add_contact': 'పరిచయాన్ని జోడించండి',
      'contact_name': 'పరిచయస్తుడి పేరు',
      'relationship': 'సంబంధం',
      'phone_number': 'ఫోన్ నంబర్',
      'save_profile_continue': 'ప్రొఫైల్ సేవ్ చేసి కొనసాగించండి',
      'skip_for_now': 'ఇప్పటికి దాటవేయండి',
      'profile_complete': 'ప్రొఫైల్ సెటప్ పూర్తయింది',
      'ready_to_connect': 'మీ అత్యవసర ప్రొఫైల్ సిద్ధంగా ఉంది. మీరు ఇప్పుడు సహారా ఆఫ్‌లైన్ మెష్‌లో అందుబాటులో ఉన్నారు.',
      'enter_sahara_home': 'సహారా హోమ్‌కు వెళ్లండి',
      'mesh_active': 'మెష్ యాక్టివ్‌గా ఉంది',
      'mesh_inactive': 'మెష్ పనిచేయడం లేదు',
      'battery': 'బ్యాటరీ',
      'relays': 'రిలేలు',
      'peers_nearby': 'దగ్గరలో ఉన్నవారు',
      'emergency_sos': 'అత్యవసర SOS',
      'tap_sos_hint': 'ప్రాణాపాయ పరిస్థితుల్లో నొక్కండి',
      'sos_active': 'SOS యాక్టివ్‌గా ఉంది',
      'emergency_broadcast': 'అత్యవసర ప్రసారం',
      'active_badge': '{count} యాక్టివ్',
      'send_emergency_broadcast': 'అత్యవసర ప్రసారాన్ని పంపండి',
      'no_broadcasts': 'మీ ప్రాంతంలో ఎటువంటి అత్యవసర ప్రకటనలు లేవు.',
      'comm_and_contacts': 'కమ్యూనికేషన్ & పరిచయాలు',
      'messages': 'సందేశాలు',
      'conversations_count': '{count} సంభాషణలు • స్టోర్ & ఫార్వర్డ్ యాక్టివ్',
      'family': 'కుటుంబం',
      'family_reachable_count': '{reachable} / {total} మెష్‌లో అందుబాటులో ఉన్నారు',
      'nearby_people': 'దగ్గరలోని వ్యక్తులు',
      'nearby_detected_count': '{count} పరిధిలో గుర్తించబడ్డారు',
      'people_in_range': '{count} పరిధిలో కనుగొనబడిన వ్యక్తులు',
      'search_nearby_hint': 'పేరు, ఫోన్ లేదా స్థానం ద్వారా వెతకండి...',
      'no_peers_found': '"{query}" తో సరిపోలే వ్యక్తులు ఎవరూ లేరు',
      'reachable': 'అందుబాటులో ఉన్నారు',
      'unreachable': 'అందుబాటులో లేరు',
      'direct': 'నేరుగా',
      'hops': '{count} హాప్స్',
      'hop': '1 హాప్',
      'ping': 'పింగ్ చేయండి',
      'ping_sent_to': '{name} కు పింగ్ పంపబడింది',
      'message': 'సందేశం',
      'add_to_family': 'కుటుంబానికి జోడించండి',
      'added_to_family': '{name} ను కుటుంబానికి చేర్చారు',
      'broadcast_severity': 'ప్రసార తీవ్రత',
      'severity_advisory': 'సలహా',
      'severity_warning': 'హెచ్చరిక',
      'severity_evacuation': 'ఖాళీ చేయుట',
      'quick_suggestions': 'త్వరిత సలహాలు (జోడించడానికి నొక్కండి)',
      'broadcast_message': 'సందేశాన్ని ప్రసారం చేయండి',
      'enter_broadcast_hint': 'అత్యవసర సందేశాన్ని నమోదు చేయండి...',
      'broadcast_button': 'సందేశాన్ని ప్రసారం చేయండి',
      'broadcast_sent': 'ప్రసారం పంపబడింది',
      'recipients_reached': 'చేరుకున్న గ్రహీతలు',
      'relays_count': 'రిలేలు',
      'compose_another': 'మరొక ప్రసారాన్ని రాయండి',
      'return_to_home': 'హోమ్‌కు తిరిగి వెళ్లండి',
      'cancel_sos': 'SOS రద్దు చేయండి',
      'hold_for_sos': 'SOS పంపడానికి 3 సెకన్లు నొక్కి పట్టుకోండి',
      'distress_beacon_active': 'ఆపద సంకేతం ప్రసారమవుతోంది',
      'sos_broadcast_notice': 'అన్ని రిలేలలో అత్యవసర SOS యాక్టివ్‌గా ఉంది',
      'ping_all_family': 'కుటుంబ సభ్యులందరినీ పింగ్ చేయండి',
      'add_family_member': 'కుటుంబ సభ్యుడిని జోడించండి',
      'emergency_messages': 'అత్యవసర సందేశాలు',
      'p2p_notice': 'P2P ఆఫ్‌లైన్ మెష్ యాక్టివ్',
      'search': 'వెతకండి',
      'cancel': 'రద్దు చేయండి',
      'save': 'సేవ్ చేయండి',
    },
  };
}

extension LocalizationExtension on BuildContext {
  String tr(String key, [Map<String, String>? params]) =>
      AppLocalizations.tr(this, key, params);
}
